### ISSUE TITLE
wap_connection_check_test fails

### ISSUE THREAD

**Issue by oranjuice** [oranjuice/monero-0mq#7]
Steps:
- Update zcmq, libzmq, zproto from Github master
- Compile wap_connection_check_test:
`g++ -g -o wap_connection_check_test wap_connection_check_test.c wap_proto.c wap_client.c wap_server.c -fpermissive -lzmq -lczmq`
- Run it

@hintjens

**Comment by hintjens** [comment]
OK, when I build using this command, it also crashes. When I build using the generated make scripts, it does not crash. Good, I'm debugging the crash now.

**Comment by hintjens** [comment]
OK, found it. There was a bug in zproto, causing heap corruption. There's a pull request that fixes it.

https://github.com/zeromq/zproto/pull/249

Thanks for finding a way to reproduce.
